# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'kama_gui2.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(996, 688)
        self.label = QtWidgets.QLabel(MainWindow)
        self.label.setGeometry(QtCore.QRect(-20, 0, 641, 691))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.L_veri = QtWidgets.QLineEdit(MainWindow)
        self.L_veri.setGeometry(QtCore.QRect(100, 60, 101, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.L_veri.setFont(font)
        self.L_veri.setMaxLength(3)
        self.L_veri.setFrame(True)
        self.L_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.L_veri.setObjectName("L_veri")
        self.t2_veri = QtWidgets.QLineEdit(MainWindow)
        self.t2_veri.setGeometry(QtCore.QRect(350, 100, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.t2_veri.setFont(font)
        self.t2_veri.setMaxLength(3)
        self.t2_veri.setFrame(True)
        self.t2_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.t2_veri.setObjectName("t2_veri")
        self.t1_veri = QtWidgets.QLineEdit(MainWindow)
        self.t1_veri.setGeometry(QtCore.QRect(350, 200, 51, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.t1_veri.setFont(font)
        self.t1_veri.setMaxLength(3)
        self.t1_veri.setFrame(True)
        self.t1_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.t1_veri.setObjectName("t1_veri")
        self.b_veri = QtWidgets.QLineEdit(MainWindow)
        self.b_veri.setGeometry(QtCore.QRect(520, 90, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.b_veri.setFont(font)
        self.b_veri.setMaxLength(3)
        self.b_veri.setFrame(True)
        self.b_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.b_veri.setObjectName("b_veri")
        self.h_veri = QtWidgets.QLineEdit(MainWindow)
        self.h_veri.setGeometry(QtCore.QRect(570, 180, 41, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.h_veri.setFont(font)
        self.h_veri.setMaxLength(3)
        self.h_veri.setFrame(True)
        self.h_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.h_veri.setObjectName("h_veri")
        self.verticalLayoutWidget = QtWidgets.QWidget(MainWindow)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(680, 10, 291, 448))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_2.sizePolicy().hasHeightForWidth())
        self.label_2.setSizePolicy(sizePolicy)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.tork_veri = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.tork_veri.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.tork_veri.setFont(font)
        self.tork_veri.setMaxLength(150)
        self.tork_veri.setFrame(True)
        self.tork_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.tork_veri.setPlaceholderText("")
        self.tork_veri.setObjectName("tork_veri")
        self.horizontalLayout_2.addWidget(self.tork_veri)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_8.sizePolicy().hasHeightForWidth())
        self.label_8.setSizePolicy(sizePolicy)
        self.label_8.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_2.addWidget(self.label_8)
        self.horizontalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_5.addWidget(self.label_3)
        self.mil_veri = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.mil_veri.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.mil_veri.setFont(font)
        self.mil_veri.setMaxLength(150)
        self.mil_veri.setFrame(True)
        self.mil_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.mil_veri.setPlaceholderText("")
        self.mil_veri.setObjectName("mil_veri")
        self.horizontalLayout_5.addWidget(self.mil_veri)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_9.sizePolicy().hasHeightForWidth())
        self.label_9.setSizePolicy(sizePolicy)
        self.label_9.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_5.addWidget(self.label_9)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_4.sizePolicy().hasHeightForWidth())
        self.label_4.setSizePolicy(sizePolicy)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_6.addWidget(self.label_4)
        self.akma_veri = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.akma_veri.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.akma_veri.setFont(font)
        self.akma_veri.setMaxLength(150)
        self.akma_veri.setFrame(True)
        self.akma_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.akma_veri.setPlaceholderText("")
        self.akma_veri.setObjectName("akma_veri")
        self.horizontalLayout_6.addWidget(self.akma_veri)
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_10.sizePolicy().hasHeightForWidth())
        self.label_10.setSizePolicy(sizePolicy)
        self.label_10.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_6.addWidget(self.label_10)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_16 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_16.sizePolicy().hasHeightForWidth())
        self.label_16.setSizePolicy(sizePolicy)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_9.addWidget(self.label_16)
        self.emniyet_veri = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.emniyet_veri.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.emniyet_veri.setFont(font)
        self.emniyet_veri.setMaxLength(150)
        self.emniyet_veri.setFrame(True)
        self.emniyet_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.emniyet_veri.setPlaceholderText("")
        self.emniyet_veri.setObjectName("emniyet_veri")
        self.horizontalLayout_9.addWidget(self.emniyet_veri)
        self.label_17 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_17.sizePolicy().hasHeightForWidth())
        self.label_17.setSizePolicy(sizePolicy)
        self.label_17.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_17.setText("")
        self.label_17.setObjectName("label_17")
        self.horizontalLayout_9.addWidget(self.label_17)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(170)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_19.sizePolicy().hasHeightForWidth())
        self.label_19.setSizePolicy(sizePolicy)
        self.label_19.setObjectName("label_19")
        self.horizontalLayout_10.addWidget(self.label_19)
        self.kamaadet_veri = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kamaadet_veri.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.kamaadet_veri.setFont(font)
        self.kamaadet_veri.setMaxLength(150)
        self.kamaadet_veri.setFrame(True)
        self.kamaadet_veri.setAlignment(QtCore.Qt.AlignCenter)
        self.kamaadet_veri.setPlaceholderText("")
        self.kamaadet_veri.setObjectName("kamaadet_veri")
        self.horizontalLayout_10.addWidget(self.kamaadet_veri)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(50)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMaximumSize(QtCore.QSize(25, 16777215))
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_10.addWidget(self.label_20)
        self.verticalLayout.addLayout(self.horizontalLayout_10)
        self.hesapla_buton = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.hesapla_buton.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.hesapla_buton.setFont(font)
        self.hesapla_buton.setObjectName("hesapla_buton")
        self.verticalLayout.addWidget(self.hesapla_buton)
        self.kaydet = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.kaydet.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.kaydet.setFont(font)
        self.kaydet.setObjectName("kaydet")
        self.verticalLayout.addWidget(self.kaydet)
        spacerItem = QtWidgets.QSpacerItem(40, 10, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.verticalLayout.addItem(spacerItem)
        self.label_14 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout.addWidget(self.label_14)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_5.sizePolicy().hasHeightForWidth())
        self.label_5.setSizePolicy(sizePolicy)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_3.addWidget(self.label_5)
        self.kesme_sonuc_label = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.kesme_sonuc_label.setEnabled(False)
        self.kesme_sonuc_label.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("TechnicBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.kesme_sonuc_label.setFont(font)
        self.kesme_sonuc_label.setMaxLength(10)
        self.kesme_sonuc_label.setFrame(True)
        self.kesme_sonuc_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.kesme_sonuc_label.setPlaceholderText("")
        self.kesme_sonuc_label.setObjectName("kesme_sonuc_label")
        self.horizontalLayout_3.addWidget(self.kesme_sonuc_label)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_11.sizePolicy().hasHeightForWidth())
        self.label_11.setSizePolicy(sizePolicy)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_3.addWidget(self.label_11)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_7.addWidget(self.label_6)
        self.p1_sonuc_label = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.p1_sonuc_label.setEnabled(False)
        self.p1_sonuc_label.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("TechnicBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.p1_sonuc_label.setFont(font)
        self.p1_sonuc_label.setMaxLength(10)
        self.p1_sonuc_label.setFrame(True)
        self.p1_sonuc_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p1_sonuc_label.setPlaceholderText("")
        self.p1_sonuc_label.setObjectName("p1_sonuc_label")
        self.horizontalLayout_7.addWidget(self.p1_sonuc_label)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_12.sizePolicy().hasHeightForWidth())
        self.label_12.setSizePolicy(sizePolicy)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_7.addWidget(self.label_12)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(100)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_7.sizePolicy().hasHeightForWidth())
        self.label_7.setSizePolicy(sizePolicy)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.p2_sonuc_label = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.p2_sonuc_label.setEnabled(False)
        self.p2_sonuc_label.setMaximumSize(QtCore.QSize(125, 16777215))
        font = QtGui.QFont()
        font.setFamily("TechnicBold")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        font.setStrikeOut(False)
        self.p2_sonuc_label.setFont(font)
        self.p2_sonuc_label.setMaxLength(10)
        self.p2_sonuc_label.setFrame(True)
        self.p2_sonuc_label.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.p2_sonuc_label.setPlaceholderText("")
        self.p2_sonuc_label.setObjectName("p2_sonuc_label")
        self.horizontalLayout_8.addWidget(self.p2_sonuc_label)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(20)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_13.sizePolicy().hasHeightForWidth())
        self.label_13.setSizePolicy(sizePolicy)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_8.addWidget(self.label_13)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.durum = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Berlin Sans FB")
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.durum.setFont(font)
        self.durum.setAutoFillBackground(False)
        self.durum.setStyleSheet("background-color: rgb(0, 170, 255);\n"
"color: rgb(255, 255, 255);")
        self.durum.setAlignment(QtCore.Qt.AlignCenter)
        self.durum.setObjectName("durum")
        self.horizontalLayout_4.addWidget(self.durum)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_15 = QtWidgets.QLabel(MainWindow)
        self.label_15.setEnabled(True)
        self.label_15.setGeometry(QtCore.QRect(610, 470, 385, 221))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_15.sizePolicy().hasHeightForWidth())
        self.label_15.setSizePolicy(sizePolicy)
        self.label_15.setMaximumSize(QtCore.QSize(385, 221))
        self.label_15.setText("")
        self.label_15.setPixmap(QtGui.QPixmap(":/kuvvet/resimler/kuvvet.jpg"))
        self.label_15.setScaledContents(True)
        self.label_15.setObjectName("label_15")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "KAMA HESAP PROGRAMI"))
        MainWindow.setWindowIcon(QtGui.QIcon(":/kuvvet/resimler/icon.ico"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><img src=\":/kama_olculer/resimler/kama_olcu.jpg\"/></p></body></html>"))
        self.L_veri.setPlaceholderText(_translate("MainWindow", "L"))
        self.t2_veri.setPlaceholderText(_translate("MainWindow", "t2"))
        self.t1_veri.setPlaceholderText(_translate("MainWindow", "t1"))
        self.b_veri.setPlaceholderText(_translate("MainWindow", "b"))
        self.h_veri.setPlaceholderText(_translate("MainWindow", "h"))
        self.label_2.setText(_translate("MainWindow", "TORK"))
        self.label_8.setText(_translate("MainWindow", "Nmm"))
        self.label_3.setText(_translate("MainWindow", "MİL ÇAPI"))
        self.label_9.setText(_translate("MainWindow", "mm"))
        self.label_4.setText(_translate("MainWindow", "KAMA AKMA GERİLMESİ"))
        self.label_10.setText(_translate("MainWindow", "MPa"))
        self.label_16.setText(_translate("MainWindow", "EMNİYET KATSAYISI"))
        self.label_19.setText(_translate("MainWindow", "KAMA SAYISI"))
        self.label_20.setText(_translate("MainWindow", "adet"))
        self.hesapla_buton.setText(_translate("MainWindow", "HESAPLA"))
        self.kaydet.setText(_translate("MainWindow", "KAYDET"))
        self.label_14.setText(_translate("MainWindow", "SONUÇLAR"))
        self.label_5.setText(_translate("MainWindow", "KESME GERİLMESİ"))
        self.label_11.setText(_translate("MainWindow", "MPa"))
        self.label_6.setText(_translate("MainWindow", "P1"))
        self.label_12.setText(_translate("MainWindow", "MPa"))
        self.label_7.setText(_translate("MainWindow", "P2"))
        self.label_13.setText(_translate("MainWindow", "MPa"))
        self.durum.setText(_translate("MainWindow", "DURUM"))
        self.hesapla_buton.clicked.connect(self.kama_hesapla)
        self.kaydet.clicked.connect(self.dosyayaYaz)

    def kama_hesapla(self):

        # verileri alıyoruz
        L = self.L_veri.text()
        b = self.b_veri.text()
        t1 = self.t1_veri.text()
        t2 = self.t2_veri.text()
        h = self.h_veri.text()
        d1 = self.mil_veri.text()
        kama_adet = self.kamaadet_veri.text()
        tork = self.tork_veri.text()
        akma = self.akma_veri.text()
        emniyet_k = self.emniyet_veri.text()

        # ondalık sayıda virgülleri değiştirme
        t1 = t1.replace(",", ".")
        t2 = t2.replace(",", ".")
        d1 = d1.replace(",", ".")
        tork = tork.replace(",", ".")

        try:

            # hesaplamalar
            milkesme_kuvveti = float(tork) / (float(d1) / 2)
            kesme_gerilmesi = int(milkesme_kuvveti) / ((int(L) * int(b)) / int(kama_adet))
            p1 = int(milkesme_kuvveti) / ((float(t2) * int(L)) / int(kama_adet))
            p2 = int(milkesme_kuvveti) / ((float(t1) * int(L)) / int(kama_adet))
            emniyet_durum = int(akma) / int(emniyet_k)

            # ekrana yazdırma
            self.kesme_sonuc_label.setText(str(kesme_gerilmesi))
            self.p1_sonuc_label.setText(str(p1))
            self.p2_sonuc_label.setText(str(p2))

            if int(emniyet_durum) > p2:
                self.durum.setText("EMNiYETLi")
                emniyet = "EMNİYETLİ"

            else:
                self.durum.setText("EMNiYETSiZ")
                emniyet = "EMNİYETSİZ"

        except:
            self.durum.setText("HATALI")

    def dosyayaYaz(self):
        dosya = open("kama_rapor.txt", "w")
        dosya.write("---------------KAMA RAPORU---------------" + '\n')
        dosya.write("*****VERİLER*****" + '\n')
        dosya.write(
            "Kama Boyu (L): " + self.L_veri.text() + '\n' + "Kama Eni (b): " + self.b_veri.text() + '\n' + "t1: " + self.t2_veri.text() + '\n' + "t2: " + self.h_veri.text() + '\n' )
        dosya.write(
            "Tork: " + self.tork_veri.text() + " Nmm" + '\n' + "Mil Çapı (d1): " + self.mil_veri.text() + " mm" + '\n' + "Kama Akma Gerilmesi: " + self.akma_veri.text() + " MPa" + '\n' + "Kama Emniyet Katsayısı: " + self.emniyet_veri.text() + '\n' + "Kama Sayısı: " + self.kamaadet_veri.text() + " Adet" + '\n'  + '\n' )
        dosya.write("*****SONUÇLAR*****" + '\n')
        dosya.write(
            "Kesme Gerilmesi: " + self.kesme_sonuc_label.text() + " Nmm" + '\n' + "P1: " + self.p1_sonuc_label.text() + " MPa" + '\n' + "P2: " + self.p2_sonuc_label.text() + " MPa" + '\n'  + '\n' )
        dosya.write("DURUM: " + self.durum.text())

        dosya.close()


import kaynak

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QDialog()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

